
version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      $SHELL -c "python manage.py makemigrations  --noinput
      && python manage.py migrate  --noinput
      && python manage.py shell < createsuperuser.py
      && python manage.py collectstatic  --noinput
      && gunicorn pos.wsgi:application --bind 0.0.0.0:8000"
