
version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "python3 manage.py makemigrations  --noinput
      && python3 manage.py migrate  --noinput
      && python3 manage.py shell < createsuperuser.py
      && python3 manage.py runserver 0.0.0.0:8000"
