# Generated by Django 4.1.4 on 2022-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('temperature', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
