# Generated by Django 4.1.4 on 2022-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='temperature',
            field=models.CharField(max_length=15),
        ),
    ]
