# Generated by Django 4.1.4 on 2022-12-25 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_forecast_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='city',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='forecast',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 25, 1, 12, 8, 289245)),
        ),
    ]
